# Proyek Analisis Data: Air Quality
- **Nama:** Azarine Nasya Aziza
- **Email:** CDCC006D6X2179@student.devacademy.id
- **ID Dicoding:** CDCC006D6X2179

## Menentukan Pertanyaan Bisnis

**SMART Question** adalah sebuah framework untuk merumuskan pertanyaan secara terstruktur agar memeperoleh informasi yang mendalam.

* **Spesific (Spesifik)**
  * Pertanyaan harus jelas, fokus pada sebuah topik tertentu, dan tidak bermakna ganda. Hindari pertanyaan yang terlalu luas.
    * Salah: Bagaimana cara meningkatkan penjualan?
    * Benar: Faktor apa saja yang memengaruhi penurunan penjualan produk kategori elektronik di wilayah Jakarta selama kuartal terakhir?
* **Measurable (Terukur)**
  * Pertanyaan harus bisa dijawab dengan angka atau matrix yang konkret, harus tahu apa yang akan dihitung.
    * Salah: Apakah pelanggan senang dengan layanan kita?
    * Benar: Berapa skor rata-rata Customer Satisfaction untuk layanan purna jual bulan ini dibandingkan bulan lalu?
* **Action-Oriented (Berorientasi Aksi)**
  * Hasil dari pertanyaan harus bisa memberikan arahan untuk melakukan tindakan nyata. Jika pertanyaan terjawab, stakeholder harus tahu apa langkah selanjutnya.
    * Salah: Mengapa orang suka berbelanja?
    * Benar: Fitur apa pada aplikasi yang paling sering digunakan sebelum pengguna memutuskan untuk melakukan checkout?
* **Relevant (Relevan)**
  * Hasil dari pertanyaan harus sejalan dengan tujuan utama bisnis atau masalah yang sedang dihadapi.
    * Salah: Menanyakan tentang stok gudang saat masalah utamanya adalah efektivitas kampanye media sosial.
    * Benar: Apakah kampanye iklan di Instagram memberikan Return on Ad Spend (ROAS) yang lebih tinggi dibandingkan iklan di TikTok?
* **Time-bound (Terikat Waktu)**
  * Pertanyaan harus ada batasan waktu yang jelas agar analisis memiliki konteks yang tepat.
    * Salah: Berapa banyak pengguna baru kita?
    * Benar: Berapa tingkat pertumbuhan pengguna baru secara bulanan (Month-over-Month) sepanjang tahun 2025?

**Contoh pertanyaan bisnis yang memenuhi seluruh elemen SMART**

***"Faktor apa saja yang memengaruhi penurunan conversion rate pada pengguna aplikasi Android di wilayah Jabodetabek sebesar 5% selama periode Flash Sale Maret 2026?"***

Keterangan:

- **Specific**: Fokus pada "penurunan conversion rate" untuk "aplikasi Android" di "Jabodetabek". Bukan sekadar penjualan turun.
- **Measurable**: Ada angka konkret yang ingin dianalisis, yaitu penurunan sebesar "5%".
- **Action-Oriented**: Dengan mengetahui faktor penyebabnya misalnya bug pada versi Android tertentu atau kendala logistik di Jabodetabek, tim bisa langsung melakukan perbaikan teknis atau operasional.
- **Relevant**: Penurunan konversi saat Flash Sale adalah masalah kritis bagi bisnis retail/e-commerce.
- **Time-bound**: Dibatasi pada periode spesifik "Flash Sale Maret 2026".

### Pertanyaan Bisnis untuk Dataset Air Quality

- **Pertanyaan 1:** Apakah rata-rata konsentrasi emisi gas buang kendaraan (NO2 dan CO) pada jam sibuk di stasiun pusat kota secara presentasi lebih tiggi dibandingkan dengan stasiun area pinggiran?
- **Pertanyaan 2:** Berapa presentasi waktu (dalam jam) dan total hari terjadinya kondisi saat konsentrasi NO2 melampaui 80 µg/m³ bersamaan dengan keceatan angin di bawah 1.5 m/s pada hari kerja selama musim dingin?

## Import Semua Packages/Library yang Digunakan

In [ ]:
# Impor library
!pip install gdown

import gdown
import zipfile
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.28.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.2.25)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [ ]:
# Impor data
# 1. Mengunduh ZIP file dari Google Drive
# File ID diambil melalui sumber dataset yang diberikan
file_id = '1RhU3gJlkteaAQfyn9XOVAz7a5o1-etgr'
output_zip_path = 'air_quality_data.zip'

print(f"Downloading air quality data (ID: {file_id})...")
gdown.download(f'https://drive.google.com/uc?id={file_id}', output_zip_path, quiet=False)
print("Download complete.")

# 2. Membuat direktori untuk mengekstrak dokumen
extract_dir = 'air_quality_data_extracted'
os.makedirs(extract_dir, exist_ok=True)

# 3. Membuka ZIP file
print(f"Extracting contents of {output_zip_path} to {extract_dir}...")
with zipfile.ZipFile(output_zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)
print("Extraction complete.")

# 4. Melihat daftar dataset dan mencari CSV secara rekursif
print("\nMencari file CSV...")
csv_files_paths = []
for root, _, files in os.walk(extract_dir):
    for file in files:
        if file.endswith('.csv'):
            csv_files_paths.append(os.path.join(root, file))

dataframes = {}
if csv_files_paths:
    print("File CSV ditemukan:")
    for path in csv_files_paths:
        print(f"- {path}")
        # Menggunakan nama file sebagai kunci di kamus dataframes
        file_name = os.path.basename(path).replace('.csv', '')
        try:
            dataframes[file_name] = pd.read_csv(path)
            print(f"  '{file_name}' berhasil dimuat. Bentuk: {dataframes[file_name].shape}")
        except Exception as e:
            print(f"  Gagal memuat '{file_name}': {e}")

    if dataframes:
        print("\nSemua data berhasil dimuat ke dalam kamus 'dataframes'.")
        # Untuk kemudahan, set 'df' ke DataFrame pertama yang dimuat (jika ada)
        # Ini akan memastikan sel penilaian sebelumnya masih bisa berfungsi untuk satu df
        # Namun, untuk penilaian seluruhnya, kita akan iterasi 'dataframes'.
        df = next(iter(dataframes.values()))
    else:
        print("Tidak ada DataFrame yang berhasil dimuat.")
        df = None
else:
    print("\nTidak ada file CSV yang ditemukan di direktori hasil ekstraksi.")
    df = None

Downloading air quality data (ID: 1RhU3gJlkteaAQfyn9XOVAz7a5o1-etgr)...

Downloading...
From: https://drive.google.com/uc?id=1RhU3gJlkteaAQfyn9XOVAz7a5o1-etgr
To: /content/air_quality_data.zip
100%|██████████| 7.96M/7.96M [00:00<00:00, 30.9MB/s]

Download complete.
Extracting contents of air_quality_data.zip to air_quality_data_extracted...
Extraction complete.

Mencari file CSV...
File CSV ditemukan:
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Gucheng_20130301-20170228.csv
  'PRSA_Data_Gucheng_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Shunyi_20130301-20170228.csv
  'PRSA_Data_Shunyi_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Dingling_20130301-20170228.csv
  'PRSA_Data_Dingling_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Aotizhongxin_20130301-20170228.csv
  'PRSA_Data_Aotizhongxin_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Wanshouxigong_20130301-20170228.csv
  'PRSA_Data_Wanshouxigong_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Changping_20130301-20170228.csv
  'PRSA_Data_Changping_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Tiantan_20130301-20170228.csv
  'PRSA_Data_Tiantan_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Wanliu_20130301-20170228.csv
  'PRSA_Data_Wanliu_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Nongzhanguan_20130301-20170228.csv
  'PRSA_Data_Nongzhanguan_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Dongsi_20130301-20170228.csv
  'PRSA_Data_Dongsi_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Guanyuan_20130301-20170228.csv
  'PRSA_Data_Guanyuan_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)
- air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Huairou_20130301-20170228.csv
  'PRSA_Data_Huairou_20130301-20170228' berhasil dimuat. Bentuk: (35064, 18)

Semua data berhasil dimuat ke dalam kamus 'dataframes'.

## Data Wrangling

### Gathering Data

#### Load df

In [ ]:
# Membuat variabel baru untuk membaca data dari salah satu file CSV yang diekstrak

changping_file_path = '/content/air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Changping_20130301-20170228.csv'
changping_df = pd.read_csv(changping_file_path)

print(f"Data dari {changping_file_path} berhasil dimuat ke variabel 'changping_df'.")
print("Berikut 5 baris pertama dari 'changping_df':")
print(changping_df.head())

Data dari /content/air_quality_data_extracted/PRSA_Data_20130301-20170228/PRSA_Data_Changping_20130301-20170228.csv berhasil dimuat ke variabel 'changping_df'.
Berikut 5 baris pertama dari 'changping_df':
   No  year  month  day  hour  PM2.5  PM10   SO2   NO2     CO    O3  TEMP  \
0   1  2013      3    1     0    3.0   6.0  13.0   7.0  300.0  85.0  -2.3
1   2  2013      3    1     1    3.0   3.0   6.0   6.0  300.0  85.0  -2.5
2   3  2013      3    1     2    3.0   3.0  22.0  13.0  400.0  74.0  -3.0
3   4  2013      3    1     3    3.0   6.0  12.0   8.0  300.0  81.0  -3.6
4   5  2013      3    1     4    3.0   3.0  14.0   8.0  300.0  81.0  -3.5

     PRES  DEWP  RAIN   wd  WSPM    station
0  1020.8 -19.7   0.0    E   0.5  Changping
1  1021.3 -19.0   0.0  ENE   0.7  Changping
2  1021.3 -19.9   0.0  ENE   0.2  Changping
3  1021.8 -19.1   0.0  NNE   1.0  Changping
4  1022.3 -19.4   0.0    N   2.1  Changping

### Assessing Data

#### Identifying the problem

In [ ]:
print('--- Assessing Data for All CSV Files ---')

if 'dataframes' in locals() and dataframes:
    for name, df_item in dataframes.items():
        print(f"\n=== {name} ===")
        print('\n--- Informasi DataFrame ---')
        df_item.info()

        print('\n--- Missing Values per Kolom ---')
        print(df_item.isnull().sum())

        print('\n--- Jumlah Data Duplikat ---')
        print(f'Jumlah baris duplikat: {df_item.duplicated().sum()}')

        print('\n--- Statistik Deskriptif untuk Kolom Numerik ---')
        display(df_item.describe())

        print('\n--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---')
        display(df_item.describe(include='all'))
else:
    print("Tidak ada DataFrame yang ditemukan untuk dinilai. Pastikan sel loading data sudah dijalankan.")

--- Assessing Data for All CSV Files ---

=== PRSA_Data_Gucheng_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34418 non-null  float64
 6   PM10     34683 non-null  float64
 7   SO2      34557 non-null  float64
 8   NO2      34396 non-null  float64
 9   CO       33663 non-null  float64
 10  O3       34335 non-null  float64
 11  TEMP     35013 non-null  float64
 12  PRES     35014 non-null  float64
 13  DEWP     35013 non-null  float64
 14  RAIN     35021 non-null  float64
 15  wd       34905 non-null  object
 16  WSPM     35022 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       646
PM10        381
SO2         507
NO2         668
CO         1401
O3          729
TEMP         51
PRES         50
DEWP         51
RAIN         43
wd          159
WSPM         42
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34418.000000,34683.000000,34557.000000,34396.000000,33663.000000,34335.000000,35013.000000,35014.000000,35013.000000,35021.000000,35022.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,83.852089,118.861978,15.366162,55.871075,1323.974423,57.694879,13.864524,1008.829592,2.610442,0.064453,1.343310
std,10122.249256,1.177213,3.448752,8.800218,6.922285,82.796445,96.742626,21.204526,36.473860,1208.957772,57.019587,11.292857,10.103256,13.782991,0.838654,1.151064
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.285600,2.000000,100.000000,0.214200,-15.600000,984.000000,-34.600000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,24.000000,45.000000,2.000000,26.000000,600.000000,10.000000,3.600000,1000.500000,-8.900000,0.000000,0.600000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,60.000000,99.000000,7.000000,50.000000,900.000000,45.000000,14.800000,1008.500000,3.000000,0.000000,1.000000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,115.750000,167.000000,20.000000,79.000000,1600.000000,83.000000,23.500000,1017.000000,15.300000,0.000000,1.800000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,770.000000,994.000000,500.000000,276.000000,10000.000000,450.000000,41.600000,1038.100000,27.400000,41.900000,12.000000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34418.000000,34683.000000,34557.000000,34396.000000,33663.000000,34335.000000,35013.000000,35014.000000,35013.000000,35021.000000,34905,35022.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,Gucheng
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3949,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,83.852089,118.861978,15.366162,55.871075,1323.974423,57.694879,13.864524,1008.829592,2.610442,0.064453,NaN,1.343310,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,82.796445,96.742626,21.204526,36.473860,1208.957772,57.019587,11.292857,10.103256,13.782991,0.838654,NaN,1.151064,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.285600,2.000000,100.000000,0.214200,-15.600000,984.000000,-34.600000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,24.000000,45.000000,2.000000,26.000000,600.000000,10.000000,3.600000,1000.500000,-8.900000,0.000000,NaN,0.600000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,60.000000,99.000000,7.000000,50.000000,900.000000,45.000000,14.800000,1008.500000,3.000000,0.000000,NaN,1.000000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,115.750000,167.000000,20.000000,79.000000,1600.000000,83.000000,23.500000,1017.000000,15.300000,0.000000,NaN,1.800000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,770.000000,994.000000,500.000000,276.000000,10000.000000,450.000000,41.600000,1038.100000,27.400000,41.900000,NaN,12.000000,NaN

=== PRSA_Data_Shunyi_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34151 non-null  float64
 6   PM10     34516 non-null  float64
 7   SO2      33768 non-null  float64
 8   NO2      33699 non-null  float64
 9   CO       32886 non-null  float64
 10  O3       33575 non-null  float64
 11  TEMP     35013 non-null  float64
 12  PRES     35013 non-null  float64
 13  DEWP     35010 non-null  float64
 14  RAIN     35013 non-null  float64
 15  wd       34581 non-null  object
 16  WSPM     35020 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       913
PM10        548
SO2        1296
NO2        1365
CO         2178
O3         1489
TEMP         51
PRES         51
DEWP         54
RAIN         51
wd          483
WSPM         44
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34151.000000,34516.000000,33768.000000,33699.000000,32886.000000,33575.000000,35013.000000,35013.000000,35010.000000,35013.000000,35020.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,79.491602,98.737026,13.572039,43.908865,1187.063979,55.201321,13.387969,1013.061938,2.465036,0.061094,1.807533
std,10122.249256,1.177213,3.448752,8.800218,6.922285,81.231739,89.143718,19.572068,30.996828,1156.374102,54.873726,11.483588,10.177339,13.726622,0.761668,1.287817
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.285600,2.000000,100.000000,0.214200,-16.800000,988.000000,-36.000000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,19.000000,31.000000,2.000000,19.000000,400.000000,10.000000,3.000000,1004.700000,-8.800000,0.000000,1.000000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,55.000000,77.000000,5.000000,37.000000,800.000000,43.000000,14.400000,1012.700000,3.100000,0.000000,1.500000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,112.000000,138.000000,17.000000,62.000000,1500.000000,77.000000,23.200000,1021.000000,15.100000,0.000000,2.300000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,941.000000,999.000000,239.000000,258.000000,10000.000000,351.716400,40.600000,1042.800000,27.500000,37.300000,12.800000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34151.000000,34516.000000,33768.000000,33699.000000,32886.000000,33575.000000,35013.000000,35013.000000,35010.000000,35013.000000,34581,35020.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NNE,NaN,Shunyi
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4540,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,79.491602,98.737026,13.572039,43.908865,1187.063979,55.201321,13.387969,1013.061938,2.465036,0.061094,NaN,1.807533,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,81.231739,89.143718,19.572068,30.996828,1156.374102,54.873726,11.483588,10.177339,13.726622,0.761668,NaN,1.287817,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.285600,2.000000,100.000000,0.214200,-16.800000,988.000000,-36.000000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,19.000000,31.000000,2.000000,19.000000,400.000000,10.000000,3.000000,1004.700000,-8.800000,0.000000,NaN,1.000000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,55.000000,77.000000,5.000000,37.000000,800.000000,43.000000,14.400000,1012.700000,3.100000,0.000000,NaN,1.500000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,112.000000,138.000000,17.000000,62.000000,1500.000000,77.000000,23.200000,1021.000000,15.100000,0.000000,NaN,2.300000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,941.000000,999.000000,239.000000,258.000000,10000.000000,351.716400,40.600000,1042.800000,27.500000,37.300000,NaN,12.800000,NaN

=== PRSA_Data_Dingling_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34285 non-null  float64
 6   PM10     34408 non-null  float64
 7   SO2      34334 non-null  float64
 8   NO2      33830 non-null  float64
 9   CO       33052 non-null  float64
 10  O3       33850 non-null  float64
 11  TEMP     35011 non-null  float64
 12  PRES     35014 non-null  float64
 13  DEWP     35011 non-null  float64
 14  RAIN     35013 non-null  float64
 15  wd       34924 non-null  object
 16  WSPM     35021 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       779
PM10        656
SO2         730
NO2        1234
CO         2012
O3         1214
TEMP         53
PRES         50
DEWP         53
RAIN         51
wd          140
WSPM         43
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34285.000000,34408.000000,34334.000000,33830.000000,33052.000000,33850.000000,35011.000000,35014.000000,35011.000000,35013.000000,35021.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,65.989497,83.739723,11.749650,27.585467,904.896073,68.548371,13.686111,1007.760278,1.505495,0.060366,1.853836
std,10122.249256,1.177213,3.448752,8.800218,6.922285,72.267723,79.541685,15.519259,26.383882,903.306220,53.764424,11.365313,10.225664,13.822099,0.752899,1.309808
min,1.000000,2013.000000,1.000000,1.000000,0.000000,3.000000,2.000000,0.285600,1.026500,100.000000,0.214200,-16.600000,982.400000,-35.100000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,14.000000,26.000000,2.000000,9.000000,300.000000,31.000000,3.400000,999.300000,-10.200000,0.000000,1.000000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,41.000000,60.000000,5.000000,19.000000,600.000000,61.000000,14.700000,1007.400000,1.800000,0.000000,1.500000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,93.000000,117.000000,15.000000,38.000000,1200.000000,90.000000,23.300000,1016.000000,14.200000,0.000000,2.300000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,881.000000,905.000000,156.000000,205.000000,10000.000000,500.000000,41.400000,1036.500000,27.200000,52.100000,10.000000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34285.000000,34408.000000,34334.000000,33830.000000,33052.000000,33850.000000,35011.000000,35014.000000,35011.000000,35013.000000,34924,35021.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NNW,NaN,Dingling
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4776,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,65.989497,83.739723,11.749650,27.585467,904.896073,68.548371,13.686111,1007.760278,1.505495,0.060366,NaN,1.853836,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,72.267723,79.541685,15.519259,26.383882,903.306220,53.764424,11.365313,10.225664,13.822099,0.752899,NaN,1.309808,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,3.000000,2.000000,0.285600,1.026500,100.000000,0.214200,-16.600000,982.400000,-35.100000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,14.000000,26.000000,2.000000,9.000000,300.000000,31.000000,3.400000,999.300000,-10.200000,0.000000,NaN,1.000000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,41.000000,60.000000,5.000000,19.000000,600.000000,61.000000,14.700000,1007.400000,1.800000,0.000000,NaN,1.500000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,93.000000,117.000000,15.000000,38.000000,1200.000000,90.000000,23.300000,1016.000000,14.200000,0.000000,NaN,2.300000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,881.000000,905.000000,156.000000,205.000000,10000.000000,500.000000,41.400000,1036.500000,27.200000,52.100000,NaN,10.000000,NaN

=== PRSA_Data_Aotizhongxin_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34139 non-null  float64
 6   PM10     34346 non-null  float64
 7   SO2      34129 non-null  float64
 8   NO2      34041 non-null  float64
 9   CO       33288 non-null  float64
 10  O3       33345 non-null  float64
 11  TEMP     35044 non-null  float64
 12  PRES     35044 non-null  float64
 13  DEWP     35044 non-null  float64
 14  RAIN     35044 non-null  float64
 15  wd       34983 non-null  object
 16  WSPM     35050 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       925
PM10        718
SO2         935
NO2        1023
CO         1776
O3         1719
TEMP         20
PRES         20
DEWP         20
RAIN         20
wd           81
WSPM         14
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34139.000000,34346.000000,34129.000000,34041.000000,33288.000000,33345.000000,35044.000000,35044.000000,35044.000000,35044.000000,35050.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,82.773611,110.060391,17.375901,59.305833,1262.945145,56.353358,13.584607,1011.846920,3.123062,0.067421,1.708496
std,10122.249256,1.177213,3.448752,8.800218,6.922285,82.135694,95.223005,22.823017,37.116200,1221.436236,57.916327,11.399097,10.404047,13.688896,0.910056,1.204071
min,1.000000,2013.000000,1.000000,1.000000,0.000000,3.000000,2.000000,0.285600,2.000000,100.000000,0.214200,-16.800000,985.900000,-35.300000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,22.000000,38.000000,3.000000,30.000000,500.000000,8.000000,3.100000,1003.300000,-8.100000,0.000000,0.900000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,58.000000,87.000000,9.000000,53.000000,900.000000,42.000000,14.500000,1011.400000,3.800000,0.000000,1.400000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,114.000000,155.000000,21.000000,82.000000,1500.000000,82.000000,23.300000,1020.100000,15.600000,0.000000,2.200000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,898.000000,984.000000,341.000000,290.000000,10000.000000,423.000000,40.500000,1042.000000,28.500000,72.500000,11.200000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34139.000000,34346.000000,34129.000000,34041.000000,33288.000000,33345.000000,35044.000000,35044.000000,35044.000000,35044.000000,34983,35050.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NE,NaN,Aotizhongxin
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5140,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,82.773611,110.060391,17.375901,59.305833,1262.945145,56.353358,13.584607,1011.846920,3.123062,0.067421,NaN,1.708496,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,82.135694,95.223005,22.823017,37.116200,1221.436236,57.916327,11.399097,10.404047,13.688896,0.910056,NaN,1.204071,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,3.000000,2.000000,0.285600,2.000000,100.000000,0.214200,-16.800000,985.900000,-35.300000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,22.000000,38.000000,3.000000,30.000000,500.000000,8.000000,3.100000,1003.300000,-8.100000,0.000000,NaN,0.900000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,58.000000,87.000000,9.000000,53.000000,900.000000,42.000000,14.500000,1011.400000,3.800000,0.000000,NaN,1.400000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,114.000000,155.000000,21.000000,82.000000,1500.000000,82.000000,23.300000,1020.100000,15.600000,0.000000,NaN,2.200000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,898.000000,984.000000,341.000000,290.000000,10000.000000,423.000000,40.500000,1042.000000,28.500000,72.500000,NaN,11.200000,NaN

=== PRSA_Data_Wanshouxigong_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34368 non-null  float64
 6   PM10     34580 non-null  float64
 7   SO2      34395 non-null  float64
 8   NO2      34310 non-null  float64
 9   CO       33767 non-null  float64
 10  O3       33986 non-null  float64
 11  TEMP     35045 non-null  float64
 12  PRES     35045 non-null  float64
 13  DEWP     35045 non-null  float64
 14  RAIN     35045 non-null  float64
 15  wd       34985 non-null  object
 16  WSPM     35051 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       696
PM10        484
SO2         669
NO2         754
CO         1297
O3         1078
TEMP         19
PRES         19
DEWP         19
RAIN         19
wd           79
WSPM         13
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34368.000000,34580.000000,34395.000000,34310.00000,33767.000000,33986.000000,35045.000000,35045.000000,35045.000000,35045.000000,35051.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,85.024136,112.223459,17.148603,55.52956,1370.395031,56.229904,13.784477,1011.511804,2.707442,0.064320,1.745314
std,10122.249256,1.177213,3.448752,8.800218,6.922285,85.975981,97.593210,23.940834,35.80805,1223.139114,57.082710,11.385156,10.570928,13.704139,0.796981,1.206355
min,1.000000,2013.000000,1.000000,1.000000,0.000000,3.000000,2.000000,0.285600,2.00000,100.000000,0.214200,-16.800000,985.100000,-35.300000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,23.000000,39.000000,3.000000,28.00000,600.000000,8.000000,3.400000,1002.800000,-8.500000,0.000000,0.900000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,60.000000,91.000000,8.000000,49.00000,1000.000000,42.000000,14.800000,1011.000000,3.300000,0.000000,1.400000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,116.000000,154.000000,21.000000,77.00000,1700.000000,82.000000,23.500000,1020.000000,15.200000,0.000000,2.300000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,999.000000,961.000000,411.000000,251.00000,9800.000000,358.000000,40.600000,1042.000000,28.500000,46.400000,13.200000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34368.000000,34580.000000,34395.000000,34310.00000,33767.000000,33986.000000,35045.000000,35045.000000,35045.000000,35045.000000,34985,35051.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NE,NaN,Wanshouxigong
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3568,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,85.024136,112.223459,17.148603,55.52956,1370.395031,56.229904,13.784477,1011.511804,2.707442,0.064320,NaN,1.745314,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,85.975981,97.593210,23.940834,35.80805,1223.139114,57.082710,11.385156,10.570928,13.704139,0.796981,NaN,1.206355,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,3.000000,2.000000,0.285600,2.00000,100.000000,0.214200,-16.800000,985.100000,-35.300000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,23.000000,39.000000,3.000000,28.00000,600.000000,8.000000,3.400000,1002.800000,-8.500000,0.000000,NaN,0.900000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,60.000000,91.000000,8.000000,49.00000,1000.000000,42.000000,14.800000,1011.000000,3.300000,0.000000,NaN,1.400000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,116.000000,154.000000,21.000000,77.00000,1700.000000,82.000000,23.500000,1020.000000,15.200000,0.000000,NaN,2.300000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,999.000000,961.000000,411.000000,251.00000,9800.000000,358.000000,40.600000,1042.000000,28.500000,46.400000,NaN,13.200000,NaN

=== PRSA_Data_Changping_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34290 non-null  float64
 6   PM10     34482 non-null  float64
 7   SO2      34436 non-null  float64
 8   NO2      34397 non-null  float64
 9   CO       33543 non-null  float64
 10  O3       34460 non-null  float64
 11  TEMP     35011 non-null  float64
 12  PRES     35014 non-null  float64
 13  DEWP     35011 non-null  float64
 14  RAIN     35013 non-null  float64
 15  wd       34924 non-null  object
 16  WSPM     35021 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       774
PM10        582
SO2         628
NO2         667
CO         1521
O3          604
TEMP         53
PRES         50
DEWP         53
RAIN         51
wd          140
WSPM         43
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34290.000000,34482.000000,34436.000000,34397.000000,33543.000000,34460.000000,35011.000000,35014.000000,35011.000000,35013.000000,35021.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,71.099743,94.657871,14.958906,44.182086,1152.301345,57.940003,13.686111,1007.760278,1.505495,0.060366,1.853836
std,10122.249256,1.177213,3.448752,8.800218,6.922285,72.326926,83.441738,20.975331,29.519796,1103.056282,54.316674,11.365313,10.225664,13.822099,0.752899,1.309808
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.285600,1.847700,100.000000,0.214200,-16.600000,982.400000,-35.100000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,18.000000,34.000000,2.000000,22.000000,500.000000,15.636600,3.400000,999.300000,-10.200000,0.000000,1.000000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,46.000000,72.000000,7.000000,36.000000,800.000000,46.000000,14.700000,1007.400000,1.800000,0.000000,1.500000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,100.000000,131.000000,18.000000,60.358200,1400.000000,80.000000,23.300000,1016.000000,14.200000,0.000000,2.300000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,882.000000,999.000000,310.000000,226.000000,10000.000000,429.000000,41.400000,1036.500000,27.200000,52.100000,10.000000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34290.000000,34482.000000,34436.000000,34397.000000,33543.000000,34460.000000,35011.000000,35014.000000,35011.000000,35013.000000,34924,35021.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NNW,NaN,Changping
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4776,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,71.099743,94.657871,14.958906,44.182086,1152.301345,57.940003,13.686111,1007.760278,1.505495,0.060366,NaN,1.853836,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,72.326926,83.441738,20.975331,29.519796,1103.056282,54.316674,11.365313,10.225664,13.822099,0.752899,NaN,1.309808,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.285600,1.847700,100.000000,0.214200,-16.600000,982.400000,-35.100000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,18.000000,34.000000,2.000000,22.000000,500.000000,15.636600,3.400000,999.300000,-10.200000,0.000000,NaN,1.000000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,46.000000,72.000000,7.000000,36.000000,800.000000,46.000000,14.700000,1007.400000,1.800000,0.000000,NaN,1.500000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,100.000000,131.000000,18.000000,60.358200,1400.000000,80.000000,23.300000,1016.000000,14.200000,0.000000,NaN,2.300000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,882.000000,999.000000,310.000000,226.000000,10000.000000,429.000000,41.400000,1036.500000,27.200000,52.100000,NaN,10.000000,NaN

=== PRSA_Data_Tiantan_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34387 non-null  float64
 6   PM10     34467 non-null  float64
 7   SO2      33946 non-null  float64
 8   NO2      34320 non-null  float64
 9   CO       33938 non-null  float64
 10  O3       34221 non-null  float64
 11  TEMP     35044 non-null  float64
 12  PRES     35044 non-null  float64
 13  DEWP     35044 non-null  float64
 14  RAIN     35044 non-null  float64
 15  wd       34986 non-null  object
 16  WSPM     35050 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       677
PM10        597
SO2        1118
NO2         744
CO         1126
O3          843
TEMP         20
PRES         20
DEWP         20
RAIN         20
wd           78
WSPM         14
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34387.000000,34467.000000,33946.000000,34320.000000,33938.000000,34221.000000,35044.000000,35044.000000,35044.000000,35044.000000,35050.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,82.164911,106.363672,14.367615,53.162646,1298.303318,55.984297,13.671490,1012.547419,2.447535,0.064020,1.860785
std,10122.249256,1.177213,3.448752,8.800218,6.922285,80.921384,89.700157,20.144631,31.946224,1170.593297,59.081528,11.458418,10.266059,13.810696,0.786282,1.280368
min,1.000000,2013.000000,1.000000,1.000000,0.000000,3.000000,2.000000,0.571200,2.000000,100.000000,0.428400,-16.800000,987.100000,-35.300000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,22.000000,41.000000,3.000000,28.000000,500.000000,8.000000,3.100000,1004.000000,-8.800000,0.000000,1.000000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,59.000000,85.000000,7.000000,47.000000,900.000000,40.000000,14.600000,1012.200000,3.000000,0.000000,1.500000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,113.000000,144.000000,17.000000,71.000000,1600.000000,81.000000,23.500000,1020.900000,15.000000,0.000000,2.400000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,821.000000,988.000000,273.000000,241.000000,10000.000000,674.000000,41.100000,1042.000000,28.800000,46.400000,10.500000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34387.000000,34467.000000,33946.000000,34320.000000,33938.000000,34221.000000,35044.000000,35044.000000,35044.000000,35044.000000,34986,35050.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENE,NaN,Tiantan
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3861,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,82.164911,106.363672,14.367615,53.162646,1298.303318,55.984297,13.671490,1012.547419,2.447535,0.064020,NaN,1.860785,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,80.921384,89.700157,20.144631,31.946224,1170.593297,59.081528,11.458418,10.266059,13.810696,0.786282,NaN,1.280368,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,3.000000,2.000000,0.571200,2.000000,100.000000,0.428400,-16.800000,987.100000,-35.300000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,22.000000,41.000000,3.000000,28.000000,500.000000,8.000000,3.100000,1004.000000,-8.800000,0.000000,NaN,1.000000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,59.000000,85.000000,7.000000,47.000000,900.000000,40.000000,14.600000,1012.200000,3.000000,0.000000,NaN,1.500000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,113.000000,144.000000,17.000000,71.000000,1600.000000,81.000000,23.500000,1020.900000,15.000000,0.000000,NaN,2.400000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,821.000000,988.000000,273.000000,241.000000,10000.000000,674.000000,41.100000,1042.000000,28.800000,46.400000,NaN,10.500000,NaN

=== PRSA_Data_Wanliu_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34682 non-null  float64
 6   PM10     34780 non-null  float64
 7   SO2      34489 non-null  float64
 8   NO2      33994 non-null  float64
 9   CO       33252 non-null  float64
 10  O3       32957 non-null  float64
 11  TEMP     35044 non-null  float64
 12  PRES     35044 non-null  float64
 13  DEWP     35044 non-null  float64
 14  RAIN     35044 non-null  float64
 15  wd       34941 non-null  object
 16  WSPM     35050 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       382
PM10        284
SO2         575
NO2        1070
CO         1812
O3         2107
TEMP         20
PRES         20
DEWP         20
RAIN         20
wd          123
WSPM         14
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34682.000000,34780.000000,34489.000000,33994.000000,33252.000000,32957.000000,35044.000000,35044.000000,35044.000000,35044.000000,35050.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,83.374716,110.464618,18.376481,65.258789,1319.353513,48.873614,13.428865,1011.097536,3.266588,0.068263,1.501215
std,10122.249256,1.177213,3.448752,8.800218,6.922285,81.905568,92.795065,22.609648,37.996088,1268.114331,55.111740,11.346931,10.355247,13.678060,0.896726,1.104472
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.285600,1.642400,100.000000,0.214200,-15.800000,985.900000,-34.900000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,23.000000,40.000000,4.000000,36.000000,500.000000,4.000000,3.200000,1002.500000,-8.100000,0.000000,0.800000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,59.000000,88.000000,10.000000,60.000000,900.000000,32.000000,14.300000,1010.800000,4.000000,0.000000,1.200000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,116.000000,153.000000,23.000000,88.000000,1600.000000,73.000000,22.900000,1019.400000,15.800000,0.000000,2.000000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,957.000000,951.000000,282.000000,264.000000,10000.000000,364.000000,40.500000,1040.300000,28.500000,72.500000,11.200000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34682.000000,34780.000000,34489.000000,33994.000000,33252.000000,32957.000000,35044.000000,35044.000000,35044.000000,35044.000000,34941,35050.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NE,NaN,Wanliu
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6703,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,83.374716,110.464618,18.376481,65.258789,1319.353513,48.873614,13.428865,1011.097536,3.266588,0.068263,NaN,1.501215,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,81.905568,92.795065,22.609648,37.996088,1268.114331,55.111740,11.346931,10.355247,13.678060,0.896726,NaN,1.104472,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.285600,1.642400,100.000000,0.214200,-15.800000,985.900000,-34.900000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,23.000000,40.000000,4.000000,36.000000,500.000000,4.000000,3.200000,1002.500000,-8.100000,0.000000,NaN,0.800000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,59.000000,88.000000,10.000000,60.000000,900.000000,32.000000,14.300000,1010.800000,4.000000,0.000000,NaN,1.200000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,116.000000,153.000000,23.000000,88.000000,1600.000000,73.000000,22.900000,1019.400000,15.800000,0.000000,NaN,2.000000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,957.000000,951.000000,282.000000,264.000000,10000.000000,364.000000,40.500000,1040.300000,28.500000,72.500000,NaN,11.200000,NaN

=== PRSA_Data_Nongzhanguan_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34436 non-null  float64
 6   PM10     34624 non-null  float64
 7   SO2      34618 non-null  float64
 8   NO2      34372 non-null  float64
 9   CO       33858 non-null  float64
 10  O3       34558 non-null  float64
 11  TEMP     35044 non-null  float64
 12  PRES     35044 non-null  float64
 13  DEWP     35044 non-null  float64
 14  RAIN     35044 non-null  float64
 15  wd       34986 non-null  object
 16  WSPM     35050 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       628
PM10        440
SO2         446
NO2         692
CO         1206
O3          506
TEMP         20
PRES         20
DEWP         20
RAIN         20
wd           78
WSPM         14
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34436.000000,34624.000000,34618.000000,34372.000000,33858.000000,34558.000000,35044.000000,35044.000000,35044.000000,35044.000000,35050.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,84.838483,108.991096,18.689242,58.097172,1324.350198,58.534682,13.671490,1012.547419,2.447535,0.064020,1.860785
std,10122.249256,1.177213,3.448752,8.800218,6.922285,86.225344,95.341177,24.280665,36.297740,1245.166124,58.401448,11.458418,10.266059,13.810696,0.786282,1.280368
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.571200,2.000000,100.000000,0.214200,-16.800000,987.100000,-35.300000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,22.000000,38.000000,3.000000,29.000000,500.000000,10.000000,3.100000,1004.000000,-8.800000,0.000000,1.000000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,59.000000,85.000000,9.000000,51.000000,900.000000,45.000000,14.600000,1012.200000,3.000000,0.000000,1.500000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,116.000000,149.000000,23.000000,80.000000,1600.000000,84.000000,23.500000,1020.900000,15.000000,0.000000,2.400000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,844.000000,995.000000,257.000000,273.000000,10000.000000,390.000000,41.100000,1042.000000,28.800000,46.400000,10.500000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34436.000000,34624.000000,34618.000000,34372.000000,33858.000000,34558.000000,35044.000000,35044.000000,35044.000000,35044.000000,34986,35050.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENE,NaN,Nongzhanguan
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3861,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,84.838483,108.991096,18.689242,58.097172,1324.350198,58.534682,13.671490,1012.547419,2.447535,0.064020,NaN,1.860785,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,86.225344,95.341177,24.280665,36.297740,1245.166124,58.401448,11.458418,10.266059,13.810696,0.786282,NaN,1.280368,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.571200,2.000000,100.000000,0.214200,-16.800000,987.100000,-35.300000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,22.000000,38.000000,3.000000,29.000000,500.000000,10.000000,3.100000,1004.000000,-8.800000,0.000000,NaN,1.000000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,59.000000,85.000000,9.000000,51.000000,900.000000,45.000000,14.600000,1012.200000,3.000000,0.000000,NaN,1.500000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,116.000000,149.000000,23.000000,80.000000,1600.000000,84.000000,23.500000,1020.900000,15.000000,0.000000,NaN,2.400000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,844.000000,995.000000,257.000000,273.000000,10000.000000,390.000000,41.100000,1042.000000,28.800000,46.400000,NaN,10.500000,NaN

=== PRSA_Data_Dongsi_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34314 non-null  float64
 6   PM10     34511 non-null  float64
 7   SO2      34401 non-null  float64
 8   NO2      33463 non-null  float64
 9   CO       31867 non-null  float64
 10  O3       34400 non-null  float64
 11  TEMP     35044 non-null  float64
 12  PRES     35044 non-null  float64
 13  DEWP     35044 non-null  float64
 14  RAIN     35044 non-null  float64
 15  wd       34986 non-null  object
 16  WSPM     35050 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       750
PM10        553
SO2         663
NO2        1601
CO         3197
O3          664
TEMP         20
PRES         20
DEWP         20
RAIN         20
wd           78
WSPM         14
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34314.000000,34511.000000,34401.000000,33463.000000,31867.000000,34400.000000,35044.000000,35044.000000,35044.000000,35044.000000,35050.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,86.194297,110.336742,18.531107,53.699443,1330.069131,57.210637,13.671490,1012.547419,2.447535,0.064020,1.860785
std,10122.249256,1.177213,3.448752,8.800218,6.922285,86.575127,98.219860,22.905655,33.959230,1191.305887,58.033275,11.458418,10.266059,13.810696,0.786282,1.280368
min,1.000000,2013.000000,1.000000,1.000000,0.000000,3.000000,2.000000,0.285600,2.000000,100.000000,0.642600,-16.800000,987.100000,-35.300000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,22.000000,38.000000,4.000000,27.000000,600.000000,12.000000,3.100000,1004.000000,-8.800000,0.000000,1.000000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,61.000000,86.000000,10.000000,47.000000,1000.000000,44.125200,14.600000,1012.200000,3.000000,0.000000,1.500000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,119.000000,151.000000,24.000000,73.000000,1700.000000,81.000000,23.500000,1020.900000,15.000000,0.000000,2.400000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,737.000000,955.000000,300.000000,258.000000,10000.000000,1071.000000,41.100000,1042.000000,28.800000,46.400000,10.500000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34314.000000,34511.000000,34401.000000,33463.000000,31867.000000,34400.000000,35044.000000,35044.000000,35044.000000,35044.000000,34986,35050.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ENE,NaN,Dongsi
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3861,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,86.194297,110.336742,18.531107,53.699443,1330.069131,57.210637,13.671490,1012.547419,2.447535,0.064020,NaN,1.860785,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,86.575127,98.219860,22.905655,33.959230,1191.305887,58.033275,11.458418,10.266059,13.810696,0.786282,NaN,1.280368,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,3.000000,2.000000,0.285600,2.000000,100.000000,0.642600,-16.800000,987.100000,-35.300000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,22.000000,38.000000,4.000000,27.000000,600.000000,12.000000,3.100000,1004.000000,-8.800000,0.000000,NaN,1.000000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,61.000000,86.000000,10.000000,47.000000,1000.000000,44.125200,14.600000,1012.200000,3.000000,0.000000,NaN,1.500000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,119.000000,151.000000,24.000000,73.000000,1700.000000,81.000000,23.500000,1020.900000,15.000000,0.000000,NaN,2.400000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,737.000000,955.000000,300.000000,258.000000,10000.000000,1071.000000,41.100000,1042.000000,28.800000,46.400000,NaN,10.500000,NaN

=== PRSA_Data_Guanyuan_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34448 non-null  float64
 6   PM10     34635 non-null  float64
 7   SO2      34590 non-null  float64
 8   NO2      34405 non-null  float64
 9   CO       33311 non-null  float64
 10  O3       33891 non-null  float64
 11  TEMP     35044 non-null  float64
 12  PRES     35044 non-null  float64
 13  DEWP     35044 non-null  float64
 14  RAIN     35044 non-null  float64
 15  wd       34983 non-null  object
 16  WSPM     35050 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       616
PM10        429
SO2         474
NO2         659
CO         1753
O3         1173
TEMP         20
PRES         20
DEWP         20
RAIN         20
wd           81
WSPM         14
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34448.000000,34635.000000,34590.000000,34405.000000,33311.000000,33891.000000,35044.000000,35044.000000,35044.000000,35044.000000,35050.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,82.933372,109.023303,17.590941,57.901643,1271.294377,55.795044,13.584607,1011.846920,3.123062,0.067421,1.708496
std,10122.249256,1.177213,3.448752,8.800218,6.922285,80.933497,91.573709,23.600367,35.150857,1164.854945,57.436983,11.399097,10.404047,13.688896,0.910056,1.204071
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,1.000000,2.000000,100.000000,0.214200,-16.800000,985.900000,-35.300000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,23.000000,40.000000,3.000000,31.000000,500.000000,7.000000,3.100000,1003.300000,-8.100000,0.000000,0.900000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,59.000000,89.000000,8.000000,51.000000,900.000000,41.000000,14.500000,1011.400000,3.800000,0.000000,1.400000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,115.000000,149.000000,22.000000,78.000000,1600.000000,81.000000,23.300000,1020.100000,15.600000,0.000000,2.200000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,680.000000,999.000000,293.000000,270.000000,10000.000000,415.000000,40.500000,1042.000000,28.500000,72.500000,11.200000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34448.000000,34635.000000,34590.000000,34405.000000,33311.000000,33891.000000,35044.000000,35044.000000,35044.000000,35044.000000,34983,35050.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NE,NaN,Guanyuan
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5140,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,82.933372,109.023303,17.590941,57.901643,1271.294377,55.795044,13.584607,1011.846920,3.123062,0.067421,NaN,1.708496,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,80.933497,91.573709,23.600367,35.150857,1164.854945,57.436983,11.399097,10.404047,13.688896,0.910056,NaN,1.204071,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,1.000000,2.000000,100.000000,0.214200,-16.800000,985.900000,-35.300000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,23.000000,40.000000,3.000000,31.000000,500.000000,7.000000,3.100000,1003.300000,-8.100000,0.000000,NaN,0.900000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,59.000000,89.000000,8.000000,51.000000,900.000000,41.000000,14.500000,1011.400000,3.800000,0.000000,NaN,1.400000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,115.000000,149.000000,22.000000,78.000000,1600.000000,81.000000,23.300000,1020.100000,15.600000,0.000000,NaN,2.200000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,680.000000,999.000000,293.000000,270.000000,10000.000000,415.000000,40.500000,1042.000000,28.500000,72.500000,NaN,11.200000,NaN

=== PRSA_Data_Huairou_20130301-20170228 ===

--- Informasi DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   No       35064 non-null  int64
 1   year     35064 non-null  int64
 2   month    35064 non-null  int64
 3   day      35064 non-null  int64
 4   hour     35064 non-null  int64
 5   PM2.5    34111 non-null  float64
 6   PM10     34287 non-null  float64
 7   SO2      34084 non-null  float64
 8   NO2      33425 non-null  float64
 9   CO       33642 non-null  float64
 10  O3       33913 non-null  float64
 11  TEMP     35013 non-null  float64
 12  PRES     35011 non-null  float64
 13  DEWP     35011 non-null  float64
 14  RAIN     35009 non-null  float64
 15  wd       34762 non-null  object
 16  WSPM     35015 non-null  float64
 17  station  35064 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 4.8+ MB

--- Missing Values per Kolom ---
No            0
year          0
month         0
day           0
hour          0
PM2.5       953
PM10        777
SO2         980
NO2        1639
CO         1422
O3         1151
TEMP         51
PRES         53
DEWP         53
RAIN         55
wd          302
WSPM         49
station       0
dtype: int64

--- Jumlah Data Duplikat ---
Jumlah baris duplikat: 0

--- Statistik Deskriptif untuk Kolom Numerik ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34111.000000,34287.000000,34084.000000,33425.000000,33642.000000,33913.000000,35013.000000,35011.000000,35011.000000,35009.000000,35015.000000
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,69.626367,91.482690,12.121553,32.497250,1022.554545,59.824713,12.445426,1007.598568,2.238619,0.067940,1.652021
std,10122.249256,1.177213,3.448752,8.800218,6.922285,71.224916,83.289578,18.896912,26.489531,898.738241,54.605746,11.751103,10.022101,14.052541,0.849046,1.199143
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.285600,1.026500,100.000000,0.214200,-19.900000,982.800000,-43.400000,0.000000,0.000000
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,17.000000,28.000000,2.000000,12.000000,400.000000,18.000000,2.100000,999.300000,-9.600000,0.000000,0.900000
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,47.000000,69.000000,4.000000,25.000000,800.000000,49.000000,13.600000,1007.300000,2.700000,0.000000,1.300000
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,98.000000,131.000000,14.000000,46.000000,1300.000000,83.000000,22.300000,1015.500000,15.300000,0.000000,2.000000
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,762.000000,993.000000,315.000000,231.000000,10000.000000,444.000000,40.300000,1036.500000,29.100000,45.900000,12.900000

--- Statistik Deskriptif untuk Semua Kolom (termasuk non-numerik) ---

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,34111.000000,34287.000000,34084.000000,33425.000000,33642.000000,33913.000000,35013.000000,35011.000000,35011.000000,35009.000000,34762,35015.000000,35064
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,1
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NW,NaN,Huairou
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4943,NaN,35064
mean,17532.500000,2014.662560,6.522930,15.729637,11.500000,69.626367,91.482690,12.121553,32.497250,1022.554545,59.824713,12.445426,1007.598568,2.238619,0.067940,NaN,1.652021,NaN
std,10122.249256,1.177213,3.448752,8.800218,6.922285,71.224916,83.289578,18.896912,26.489531,898.738241,54.605746,11.751103,10.022101,14.052541,0.849046,NaN,1.199143,NaN
min,1.000000,2013.000000,1.000000,1.000000,0.000000,2.000000,2.000000,0.285600,1.026500,100.000000,0.214200,-19.900000,982.800000,-43.400000,0.000000,NaN,0.000000,NaN
25%,8766.750000,2014.000000,4.000000,8.000000,5.750000,17.000000,28.000000,2.000000,12.000000,400.000000,18.000000,2.100000,999.300000,-9.600000,0.000000,NaN,0.900000,NaN
50%,17532.500000,2015.000000,7.000000,16.000000,11.500000,47.000000,69.000000,4.000000,25.000000,800.000000,49.000000,13.600000,1007.300000,2.700000,0.000000,NaN,1.300000,NaN
75%,26298.250000,2016.000000,10.000000,23.000000,17.250000,98.000000,131.000000,14.000000,46.000000,1300.000000,83.000000,22.300000,1015.500000,15.300000,0.000000,NaN,2.000000,NaN
max,35064.000000,2017.000000,12.000000,31.000000,23.000000,762.000000,993.000000,315.000000,231.000000,10000.000000,444.000000,40.300000,1036.500000,29.100000,45.900000,NaN,12.900000,NaN

### Cleaning Data

In [ ]:
combined_df = pd.concat(dataframes.values(), ignore_index=True)

print("5 baris pertama dari combined_df:")
print(combined_df.head())
print(f"\nBentuk combined_df: {combined_df.shape}")

5 baris pertama dari combined_df:
   No  year  month  day  hour  PM2.5  PM10  SO2  NO2     CO    O3  TEMP  \
0   1  2013      3    1     0    6.0  18.0  5.0  NaN  800.0  88.0   0.1
1   2  2013      3    1     1    6.0  15.0  5.0  NaN  800.0  88.0  -0.3
2   3  2013      3    1     2    5.0  18.0  NaN  NaN  700.0  52.0  -0.7
3   4  2013      3    1     3    6.0  20.0  6.0  NaN    NaN   NaN  -1.0
4   5  2013      3    1     4    5.0  17.0  5.0  NaN  600.0  73.0  -1.3

     PRES  DEWP  RAIN   wd  WSPM  station
0  1021.1 -18.6   0.0   NW   4.4  Gucheng
1  1021.5 -19.0   0.0   NW   4.0  Gucheng
2  1021.5 -19.8   0.0  WNW   4.6  Gucheng
3  1022.7 -21.2   0.0    W   2.8  Gucheng
4  1023.0 -21.4   0.0  WNW   3.6  Gucheng

Bentuk combined_df: (420768, 18)

In [ ]:
if 'year' in combined_df.columns and 'month' in combined_df.columns and 'day' in combined_df.columns and 'hour' in combined_df.columns:
    combined_df['datetime'] = pd.to_datetime(combined_df[['year', 'month', 'day', 'hour']])
    combined_df = combined_df.drop(columns=['year', 'month', 'day', 'hour'])
    print("  -> Kolom 'datetime' berhasil dibuat dan kolom waktu asli dihapus.")
else:
    print("  -> Kolom tahun, bulan, hari, atau jam tidak ditemukan. Kolom 'datetime' diasumsikan sudah ada.")

  -> Kolom 'datetime' berhasil dibuat dan kolom waktu asli dihapus.

In [ ]:
# Membuat kolom turunan untuk 'hari dalam seminggu' dan 'musim'
if 'datetime' in combined_df.columns:
    if 'day_of_week' not in combined_df.columns:
        combined_df['day_of_week'] = combined_df['datetime'].dt.day_name()
        print("  -> Kolom 'day_of_week' berhasil dibuat.")
    else:
        print("  -> Kolom 'day_of_week' sudah ada.")

    if 'is_weekday' not in combined_df.columns:
        combined_df['is_weekday'] = combined_df['datetime'].dt.dayofweek < 5
        print("  -> Kolom 'is_weekday' berhasil dibuat.")
    else:
        print("  -> Kolom 'is_weekday' sudah ada.")

    def get_season(month):
        if month in [12, 1, 2]:
            return 'Winter'
        elif month in [3, 4, 5]:
            return 'Spring'
        elif month in [6, 7, 8]:
            return 'Summer'
        else:
            return 'Autumn'

    if 'season' not in combined_df.columns:
        combined_df['season'] = combined_df['datetime'].dt.month.apply(get_season)
        print("  -> Kolom 'season' berhasil dibuat.")
    else:
        print("  -> Kolom 'season' sudah ada.")
else:
    print("  -> Kolom 'datetime' tidak ditemukan, melewatkan pembuatan kolom turunan waktu.")

  -> Kolom 'day_of_week' berhasil dibuat.
  -> Kolom 'is_weekday' berhasil dibuat.
  -> Kolom 'season' berhasil dibuat.

In [ ]:
# Mengidentifikasi dan mengklasifikasikan setiap stasiun sebagai 'pusat kota' atau 'pinggiran'
if 'station' in combined_df.columns and 'location_type' not in combined_df.columns:
    suburban_stations = ['Changping', 'Dingling', 'Huairou', 'Shunyi', 'Wanliu']
    city_center_stations = ['Aotizhongxin', 'Dongsi', 'Guanyuan', 'Gucheng', 'Nongzhanguan', 'Tiantan', 'Wanshouxigong']

    def classify_station_location(station_name):
        if station_name in suburban_stations:
            return 'Suburban'
        elif station_name in city_center_stations:
            return 'City Center'
        else:
            return 'Unknown'

    combined_df['location_type'] = combined_df['station'].apply(classify_station_location)
    print("  -> Kolom 'location_type' untuk stasiun berhasil dibuat.")
else:
    print("  -> Kolom 'location_type' sudah ada atau kolom 'station' tidak ditemukan.")

  -> Kolom 'location_type' untuk stasiun berhasil dibuat.

#### Fixing lost value

In [ ]:
# Menangani nilai yang hilang (missing values)
print("\n--- Menangani Nilai yang Hilang ---")
print("Jumlah nilai yang hilang sebelum imputasi:")
initial_missing = combined_df.isnull().sum()[combined_df.isnull().sum() > 0]
if not initial_missing.empty:
    print(initial_missing)
else:
    print("Tidak ada nilai yang hilang sebelum imputasi.")

numerical_cols = combined_df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = combined_df.select_dtypes(include='object').columns.tolist()

# Hapus kolom 'No' dari daftar numerik untuk imputasi jika ada
if 'No' in numerical_cols:
    numerical_cols.remove('No')

print("\n  -> Melakukan imputasi kolom numerik dengan median...")
for col in numerical_cols:
    if combined_df[col].isnull().any():
        median_val = combined_df[col].median()
        combined_df[col].fillna(median_val, inplace=True)
        print(f"    Kolom '{col}' diimputasi dengan median: {median_val}")

print("\n  -> Melakukan imputasi kolom kategorikal dengan modus...")
for col in categorical_cols:
    if combined_df[col].isnull().any():
        # Untuk 'wd' yang memiliki missing values, kita isi dengan 'Unknown' agar tidak bias pada modus
        if col == 'wd':
            combined_df[col].fillna('Unknown', inplace=True)
            print(f"    Kolom '{col}' diimputasi dengan 'Unknown'.")
        else:
            mode_val = combined_df[col].mode()[0]
            combined_df[col].fillna(mode_val, inplace=True)
            print(f"    Kolom '{col}' diimputasi dengan modus: {mode_val}")

--- Menangani Nilai yang Hilang ---
Jumlah nilai yang hilang sebelum imputasi:
PM2.5     8739
PM10      6449
SO2       9021
NO2      12116
CO       20701
O3       13277
TEMP       398
PRES       393
DEWP       403
RAIN       390
wd        1822
WSPM       318
dtype: int64

  -> Melakukan imputasi kolom numerik dengan median...
    Kolom 'PM2.5' diimputasi dengan median: 55.0
    Kolom 'PM10' diimputasi dengan median: 82.0
    Kolom 'SO2' diimputasi dengan median: 7.0
    Kolom 'NO2' diimputasi dengan median: 43.0
    Kolom 'CO' diimputasi dengan median: 900.0
    Kolom 'O3' diimputasi dengan median: 45.0
    Kolom 'TEMP' diimputasi dengan median: 14.5
    Kolom 'PRES' diimputasi dengan median: 1010.4
    Kolom 'DEWP' diimputasi dengan median: 3.1
    Kolom 'RAIN' diimputasi dengan median: 0.0
    Kolom 'WSPM' diimputasi dengan median: 1.4

  -> Melakukan imputasi kolom kategorikal dengan modus...
    Kolom 'wd' diimputasi dengan 'Unknown'.

/tmp/ipykernel_611/993632330.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  combined_df[col].fillna(median_val, inplace=True)
/tmp/ipykernel_611/993632330.py:29: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  combined_df[col].fillna('Unknown', inplace=True)

In [ ]:
print("\nJumlah nilai yang hilang setelah imputasi:")
missing_after_imputation = combined_df.isnull().sum()[combined_df.isnull().sum() > 0]
if missing_after_imputation.empty:
    print("Tidak ada nilai yang hilang setelah imputasi.")
else:
    print(missing_after_imputation)

print("\n--- Ringkasan DataFrame setelah Preprocessing dan Cleaning ---")
combined_df.info()
print("\n5 baris pertama dari combined_df setelah semua preprocessing:")
print(combined_df.head())

Jumlah nilai yang hilang setelah imputasi:
Tidak ada nilai yang hilang setelah imputasi.

--- Ringkasan DataFrame setelah Preprocessing dan Cleaning ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420768 entries, 0 to 420767
Data columns (total 19 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   No             420768 non-null  int64
 1   PM2.5          420768 non-null  float64
 2   PM10           420768 non-null  float64
 3   SO2            420768 non-null  float64
 4   NO2            420768 non-null  float64
 5   CO             420768 non-null  float64
 6   O3             420768 non-null  float64
 7   TEMP           420768 non-null  float64
 8   PRES           420768 non-null  float64
 9   DEWP           420768 non-null  float64
 10  RAIN           420768 non-null  float64
 11  wd             420768 non-null  object
 12  WSPM           420768 non-null  float64
 13  station        420768 non-null  object
 14  datetime       420768 non-null  datetime64[ns]
 15  day_of_week    420768 non-null  object
 16  is_weekday     420768 non-null  bool
 17  season         420768 non-null  object
 18  location_type  420768 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(11), int64(1), object(5)
memory usage: 58.2+ MB

5 baris pertama dari combined_df setelah semua preprocessing:
   No  PM2.5  PM10  SO2   NO2     CO    O3  TEMP    PRES  DEWP  RAIN   wd  \
0   1    6.0  18.0  5.0  43.0  800.0  88.0   0.1  1021.1 -18.6   0.0   NW
1   2    6.0  15.0  5.0  43.0  800.0  88.0  -0.3  1021.5 -19.0   0.0   NW
2   3    5.0  18.0  7.0  43.0  700.0  52.0  -0.7  1021.5 -19.8   0.0  WNW
3   4    6.0  20.0  6.0  43.0  900.0  45.0  -1.0  1022.7 -21.2   0.0    W
4   5    5.0  17.0  5.0  43.0  600.0  73.0  -1.3  1023.0 -21.4   0.0  WNW

   WSPM  station            datetime day_of_week  is_weekday  season  \
0   4.4  Gucheng 2013-03-01 00:00:00      Friday        True  Spring
1   4.0  Gucheng 2013-03-01 01:00:00      Friday        True  Spring
2   4.6  Gucheng 2013-03-01 02:00:00      Friday        True  Spring
3   2.8  Gucheng 2013-03-01 03:00:00      Friday        True  Spring
4   3.6  Gucheng 2013-03-01 04:00:00      Friday        True  Spring

  location_type
0   City Center
1   City Center
2   City Center
3   City Center
4   City Center

## Exploratory Data Analysis (EDA)

### Explore

## Visualization & Explanatory Analysis

### Pertanyaan 1: Apakah rata-rata konsentrasi emisi gas buang kendaraan (NO2 dan CO) pada jam sibuk di stasiun pusat kota secara presentasi lebih tiggi dibandingkan dengan stasiun area pinggiran?

In [ ]:
# 1. Mendefinisikan 'jam sibuk' (07:00-09:00 dan 16:00-18:00).
rush_hour_morning = (combined_df['datetime'].dt.hour >= 7) & (combined_df['datetime'].dt.hour < 10)
rush_hour_evening = (combined_df['datetime'].dt.hour >= 16) & (combined_df['datetime'].dt.hour < 19)

In [ ]:
# 2. Memfilter data hanya untuk jam sibuk.
rush_hour_df = combined_df[rush_hour_morning | rush_hour_evening].copy()
print(f"Data jam sibuk berhasil difilter. Jumlah data: {len(rush_hour_df)} baris.")

Data jam sibuk berhasil difilter. Jumlah data: 105192 baris.

In [ ]:
# 3. Mengelompokkan data berdasarkan jenis stasiun (pusat kota vs pinggiran).
# 4. Menghitung rata-rata konsentrasi NO2 dan CO untuk masing-masing kelompok.
average_emissions = rush_hour_df.groupby('location_type')[['NO2', 'CO']].mean()
print("\nRata-rata konsentrasi NO2 dan CO selama jam sibuk berdasarkan tipe lokasi:")
print(average_emissions)

# Memisahkan rata-rata untuk pusat kota dan pinggiran
if 'City Center' in average_emissions.index and 'Suburban' in average_emissions.index:
    city_center_avg = average_emissions.loc['City Center']
    suburban_avg = average_emissions.loc['Suburban']

    print("\n--- Perbandingan Rata-rata Emisi ---")
    print(f"Rata-rata NO2 di Pusat Kota: {city_center_avg['NO2']:.2f}")
    print(f"Rata-rata NO2 di Pinggiran: {suburban_avg['NO2']:.2f}")
    print(f"Rata-rata CO di Pusat Kota: {city_center_avg['CO']:.2f}")
    print(f"Rata-rata CO di Pinggiran: {suburban_avg['CO']:.2f}")

Rata-rata konsentrasi NO2 dan CO selama jam sibuk berdasarkan tipe lokasi:
                     NO2           CO
location_type
City Center    52.398381  1237.721587
Suburban       42.407717  1078.603742

--- Perbandingan Rata-rata Emisi ---
Rata-rata NO2 di Pusat Kota: 52.40
Rata-rata NO2 di Pinggiran: 42.41
Rata-rata CO di Pusat Kota: 1237.72
Rata-rata CO di Pinggiran: 1078.60

In [ ]:
# 5. Menghitung perbandingan persentase antara rata-rata konsentrasi di stasiun pusat kota dan pinggiran.

if 'City Center' in average_emissions.index and 'Suburban' in average_emissions.index:
    # Asumsi: Menghitung persentase perbedaan relatif terhadap area pinggiran
    percentage_diff_no2 = ((city_center_avg['NO2'] - suburban_avg['NO2']) / suburban_avg['NO2']) * 100
    percentage_diff_co = ((city_center_avg['CO'] - suburban_avg['CO']) / suburban_avg['CO']) * 100

    print("\n--- Perbandingan Persentase (Pusat Kota vs Pinggiran) ---")
    print(f"Konsentrasi NO2 di Pusat Kota {'lebih tinggi' if percentage_diff_no2 > 0 else 'lebih rendah'} {abs(percentage_diff_no2):.2f}% dibandingkan Pinggiran.")
    print(f"Konsentrasi CO di Pusat Kota {'lebih tinggi' if percentage_diff_co > 0 else 'lebih rendah'} {abs(percentage_diff_co):.2f}% dibandingkan Pinggiran.")

    # Menentukan apakah secara presentase lebih tinggi
    if percentage_diff_no2 > 0 and percentage_diff_co > 0:
        print("\nKesimpulan Sementara: Rata-rata konsentrasi emisi NO2 dan CO di stasiun pusat kota secara presentasi lebih tinggi dibandingkan dengan stasiun area pinggiran.")
    elif percentage_diff_no2 < 0 and percentage_diff_co < 0:
        print("\nKesimpulan Sementara: Rata-rata konsentrasi emisi NO2 dan CO di stasiun pusat kota secara presentasi lebih rendah dibandingkan dengan stasiun area pinggiran.")
    else:
        print("\nKesimpulan Sementara: Perbandingan konsentrasi emisi NO2 dan CO di stasiun pusat kota dan pinggiran menunjukkan pola yang bervariasi.")
else:
    print("\nTidak dapat melakukan perbandingan persentase karena data untuk 'City Center' atau 'Suburban' tidak lengkap.")

--- Perbandingan Persentase (Pusat Kota vs Pinggiran) ---
Konsentrasi NO2 di Pusat Kota lebih tinggi 23.56% dibandingkan Pinggiran.
Konsentrasi CO di Pusat Kota lebih tinggi 14.75% dibandingkan Pinggiran.

Kesimpulan Sementara: Rata-rata konsentrasi emisi NO2 dan CO di stasiun pusat kota secara presentasi lebih tinggi dibandingkan dengan stasiun area pinggiran.

**Insight:**

**Rata-rata Emisi:** Selama jam sibuk (07:00-09:00 dan 16:00-18:00), rata-rata konsentrasi NO2 dan CO lebih tinggi di stasiun Pusat Kota dibandingkan stasiun Pinggiran.
    *   Rata-rata NO2 di Pusat Kota: **52,40 µg/m³**
    *   Rata-rata NO2 di Pinggiran: **42,41 µg/m³**
    *   Rata-rata CO di Pusat Kota: **1237,72 µg/m³**
    *   Rata-rata CO di Pinggiran: **1078,60 µg/m³**
*   **Perbedaan Persentase:**
    *   Konsentrasi NO2 di Pusat Kota **23,56% lebih tinggi** dibandingkan area Pinggiran.
    *   Konsentrasi CO di Pusat Kota **14,75% lebih tinggi** dibandingkan area Pinggiran.

### Pertanyaan 2: Berapa presentasi waktu (dalam jam) dan total hari terjadinya kondisi saat konsentrasi NO2 melampaui 80 µg/m³ bersamaan dengan keceatan angin di bawah 1.5 m/s pada hari kerja selama musim dingin?

In [ ]:
# 1. Memfilter data untuk 'hari kerja' dan 'musim dingin'.
winter_weekday_df = combined_df[(combined_df['is_weekday'] == True) & (combined_df['season'] == 'Winter')].copy()
print(f"Data difilter untuk hari kerja di musim dingin. Jumlah data: {len(winter_weekday_df)} baris.")

# Menghitung total jam dan hari unik yang diamati selama hari kerja di musim dingin
total_winter_weekday_hours = len(winter_weekday_df)
total_winter_weekday_days = winter_weekday_df['datetime'].dt.date.nunique()
print(f"Total jam di hari kerja musim dingin: {total_winter_weekday_hours}")
print(f"Total hari unik di hari kerja musim dingin: {total_winter_weekday_days}")

Data difilter untuk hari kerja di musim dingin. Jumlah data: 74592 baris.
Total jam di hari kerja musim dingin: 74592
Total hari unik di hari kerja musim dingin: 259

In [ ]:
# 2. Mengidentifikasi data di mana konsentrasi NO2 > 80 µg/m³ DAN kecepatan angin (WSPM) < 1.5 m/s.
# Pastikan kolom NO2 dan WSPM tidak null (meskipun sudah diimputasi, ini untuk keamanan)
condition_met_df = winter_weekday_df[
    (winter_weekday_df['NO2'] > 80) &
    (winter_weekday_df['WSPM'] < 1.5)
].copy()

print(f"Data memenuhi kondisi NO2 > 80 µg/m³ dan WSPM < 1.5 m/s: {len(condition_met_df)} baris.")

Data memenuhi kondisi NO2 > 80 µg/m³ dan WSPM < 1.5 m/s: 15627 baris.

In [ ]:
# 3. Menghitung total jam (jumlah baris) yang memenuhi kondisi ini.
total_hours_condition_met = len(condition_met_df)
print(f"Total jam yang memenuhi kondisi: {total_hours_condition_met}")

Total jam yang memenuhi kondisi: 15627

In [ ]:
# 4. Menghitung total hari unik yang memenuhi kondisi ini.
total_days_condition_met = condition_met_df['datetime'].dt.date.nunique()
print(f"Total hari unik yang memenuhi kondisi: {total_days_condition_met}")

Total hari unik yang memenuhi kondisi: 224

In [ ]:
# 5. Menghitung persentase jam dan hari tersebut terhadap total jam dan hari yang diamati selama hari kerja di musim dingin.
percentage_hours = (total_hours_condition_met / total_winter_weekday_hours) * 100 if total_winter_weekday_hours > 0 else 0
percentage_days = (total_days_condition_met / total_winter_weekday_days) * 100 if total_winter_weekday_days > 0 else 0

print(f"\nPersentase waktu (dalam jam) kondisi terpenuhi: {percentage_hours:.2f}%")
print(f"Persentase total hari kondisi terpenuhi: {percentage_days:.2f}%")

Persentase waktu (dalam jam) kondisi terpenuhi: 20.95%
Persentase total hari kondisi terpenuhi: 86.49%

**Insight:**

 **Data Terfilter:** Analisis berfokus pada **74,592 jam** di **259 hari unik** yang diklasifikasikan sebagai hari kerja musim dingin.
*   **Kejadian Kondisi Kritis:** Kondisi kritis spesifik di mana konsentrasi NO2 melebihi 80 µg/m³ dan kecepatan angin (WSPM) di bawah 1.5 m/s terjadi selama:
    *   **Total Jam:** 15,627 jam
    *   **Total Hari Unik:** 224 hari
*   **Persentase Kejadian:**
    *   Kondisi tersebut terjadi dalam **20.95%** dari total jam hari kerja musim dingin.
    *   Kondisi tersebut terjadi pada **86.49%** dari total hari kerja musim dingin.

## Analisis Lanjutan (Opsional)

## Conclusion & Recommendation

- **Conclusion pertanyaan 1:**
Berdasarkan analisis, rata-rata konsentrasi emisi gas buang kendaraan (NO2 dan CO) selama jam sibuk di stasiun pusat kota secara signifikan lebih tinggi dibandingkan di stasiun area pinggiran. Hal ini menunjukkan bahwa pusat kota mengalami polusi udara yang lebih besar dari polutan-polutan ini, terutama selama waktu lalu lintas padat, kemungkinan besar karena kepadatan lalu lintas yang lebih tinggi dan potensi sumber emisi lokal yang lebih banyak.

- **Conclusion pertanyaan 2:**
Selama hari kerja musim dingin, kondisi kritis konsentrasi NO2 tinggi (di atas 80 µg/m³) yang disertai dengan kecepatan angin rendah (di bawah 1.5 m/s) sering terjadi. Meskipun kondisi ini menyumbang sekitar **21% dari total jam**, namun berdampak pada **86.5% dari semua hari kerja musim dingin** yang substansial. Persentase hari yang tinggi ini menunjukkan bahwa kondisi lingkungan seperti itu merupakan karakteristik hari kerja musim dingin dan kemungkinan berkontribusi pada tantangan kualitas udara yang persisten, karena kecepatan angin yang rendah menghambat penyebaran polutan. Investigasi lebih lanjut mengenai waktu spesifik dalam sehari di mana kondisi ini paling sering terjadi dapat memberikan wawasan yang lebih terarah.

**Rekomendasi Action Item:**

Berdasarkan analisis kualitas udara di stasiun perkotaan dan pinggiran kota, serta kondisi NO2 tinggi saat kecepatan angin rendah di musim dingin, berikut adalah beberapa rekomendasi aksi:

1.  **Penguatan Kebijakan Transportasi dan Emisi:** Menerapkan kebijakan yang lebih ketat terkait standar emisi kendaraan, terutama di pusat kota, dan mempromosikan secara aktif penggunaan transportasi publik, sepeda, serta kendaraan listrik. Ini dapat membantu mengurangi konsentrasi NO2 dan CO pada jam sibuk.
2.  **Sistem Peringatan Dini Kualitas Udara yang Lebih Proaktif:** Mengembangkan dan mengimplementasikan sistem peringatan dini yang tidak hanya memberikan informasi real-time, tetapi juga prediksi kualitas udara, khususnya untuk kondisi 'NO2 tinggi dan angin rendah' selama musim dingin. Peringatan ini harus mencakup saran tindakan bagi warga (misalnya, mengurangi aktivitas luar ruangan, menggunakan masker).
3.  **Pengembangan Infrastruktur Hijau:** Berinvestasi dalam peningkatan ruang hijau dan vegetasi di area perkotaan yang padat. Tumbuhan dapat membantu menyaring polutan udara dan meningkatkan kualitas udara secara alami.
4.  **Penelitian Lanjutan tentang Sumber Emisi Lokal:** Melakukan studi lebih lanjut untuk mengidentifikasi sumber emisi spesifik (selain kendaraan) yang mungkin berkontribusi terhadap tingkat polusi tinggi di pusat kota, serta mencari solusi mitigasi yang ditargetkan.

In [ ]:
combined_df.to_csv('air_quality_combined.csv', index=False)
print('Data combined_df berhasil disimpan ke air_quality_combined.csv')

Data combined_df berhasil disimpan ke air_quality_combined.csv